"""Rename count_messages into messages

Revision ID: 396ec505cc4f
Revises: 23d360f13723
Create Date: 2023-12-28 19:45:20.487904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "396ec505cc4f"
down_revision: Union[str, None] = "23d360f13723"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("messages", sa.Integer(), nullable=False))
    op.drop_column("users", "count_messages")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("count_messages", sa.INTEGER(), nullable=False))
    op.drop_column("users", "messages")
    # ### end Alembic commands ###
