"""Add fields for counting messages and update time

Revision ID: 23d360f13723
Revises: dadfd84b46d5
Create Date: 2023-12-25 19:05:52.434579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "23d360f13723"
down_revision: Union[str, None] = "dadfd84b46d5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("guilds", sa.Column("updated_at", sa.DateTime(), nullable=False))
    op.add_column("users", sa.Column("count_messages", sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "count_messages")
    op.drop_column("guilds", "updated_at")
    # ### end Alembic commands ###
