"""Remove id col for secondary table

Revision ID: 48a5fc86084c
Revises: dadfd84b46d5
Create Date: 2023-12-19 23:50:33.141907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48a5fc86084c'
down_revision: Union[str, None] = 'dadfd84b46d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
