"""Replace messages from Users to secondary table

Revision ID: 8fd3b11b3aee
Revises: 5ef605f44b3d
Create Date: 2024-02-22 20:55:59.053277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fd3b11b3aee'
down_revision: Union[str, None] = '5ef605f44b3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guild_user', sa.Column('messages', sa.Integer(), nullable=False, server_default='0'))
    op.drop_column('users', 'messages')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('messages', sa.INTEGER(), nullable=False, server_default='0'))
    op.drop_column('guild_user', 'messages')
    # ### end Alembic commands ###
